sudo: required 

language: generic

services:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t koentc010/docker-react-app -f Dockerfile.dev .

srcipt:
 - docker run -e CI=true koentc010/docker-react-app npm run test -- --coverage
  
after_success:
 - echo "Test success"

deploy:
 provider: elasticbeanstalk
 region: "ap-northeast-2"
 app: "docker-react-app"
 env: "Dockerreactapp-env"
 bucket_name: "elasticbeanstalk-ap-northeast-2-215894504361"
 bucket_path: "docker-react-app"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_ACCESS_KEY