sudo: required 

language: generic

services:
 - docker

before_install:
 - echo "start creating an image with dockerfile"
 - docker build -t koentc010/docker-react-app -f Dockerfile.dev .

srcipt:
 - docker run -e CI=true koentc010/docker-react-app npm run test -- --coverage

after_success:
 - echo "Test success"
